In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
plt.style.use('ggplot')
# figサイズを10,8に設定
plt.rcParams['figure.figsize'] = [10, 8]
plt.rcParams['font.size'] = 14

In [4]:
file_path = '../dataset/house_price_jp.csv'

In [5]:
df = pd.read_csv(file_path, sep=',')

In [7]:
df.head()

,index,type,land_type,prefecture,city,city2,station_name,building_year,station_dis,price,price_per_tsubo,room,area,land_shape,frontage,gross_floor_area,building_type,city_plan,BCR,FAR
0,1,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１１丁目,2016,1,37000000,NaN,３ＬＤＫ,75,NaN,NaN,NaN,ＲＣ,商業地域,80.0,600.0
1,2,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１１丁目,2012,3,57000000,NaN,２ＬＤＫ,75,NaN,NaN,NaN,ＲＣ,商業地域,80.0,600.0
2,3,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1981,3,17000000,NaN,２ＬＤＫ,50,NaN,NaN,NaN,ＲＣ,商業地域,80.0,400.0
3,4,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1977,0,3200000,NaN,１Ｒ,20,NaN,NaN,NaN,ＳＲＣ,商業地域,80.0,400.0
4,5,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1989,2,17000000,NaN,２ＬＤＫ,50,NaN,NaN,NaN,ＳＲＣ,商業地域,80.0,400.0

In [8]:
df['Log10_price'] = df['price'].apply(lambda x: np.log10(x))

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19904 entries, 0 to 19903
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             19904 non-null  int64
 1   type              19904 non-null  object
 2   land_type         12261 non-null  object
 3   prefecture        19904 non-null  object
 4   city              19904 non-null  object
 5   city2             19903 non-null  object
 6   station_name      19769 non-null  object
 7   building_year     19904 non-null  int64
 8   station_dis       19766 non-null  object
 9   price             19904 non-null  int64
 10  price_per_tsubo   0 non-null      float64
 11  room              7209 non-null   object
 12  area              19904 non-null  object
 13  land_shape        12260 non-null  object
 14  frontage          11282 non-null  float64
 15  gross_floor_area  12113 non-null  object
 16  building_type     19242 non-null  object
 17  city_plan         19817 non-null  object
 18  BCR               19305 non-null  float64
 19  FAR               19305 non-null  float64
 20  Log10_price       19904 non-null  float64
dtypes: float64(5), int64(3), object(13)
memory usage: 3.2+ MB

### station_disとareaがobjectになっているのが気になる

In [10]:
# station_disのユニークな値を確認
df['station_dis'].unique()

array(['1', '3', '0', '2', '5', '4', '6', '11', '10', '30分?60分', '7',
       '12', '14', '18', '19', '25', '28', '26', '9', '29', '13', '20',
       '8', '16', '21', '24', '1H?1H30', '15', '22', '17', '1H30?2H',
       '23', nan, '2H?', '27', '8.0', '1.0', '14.0', '7.0', '6.0', '10.0',
       '9.0', '5.0', '3.0', '15.0'], dtype=object)

In [11]:
# 数値に変換する(coerceで数値に変換出来ないものはnanに変換)
df['station_dis'] = pd.to_numeric(df['station_dis'], errors='coerce')

In [12]:
df['station_dis'].unique()

array([ 1.,  3.,  0.,  2.,  5.,  4.,  6., 11., 10., nan,  7., 12., 14.,
       18., 19., 25., 28., 26.,  9., 29., 13., 20.,  8., 16., 21., 24.,
       15., 22., 17., 23., 27.])

In [14]:
df['area'].unique()

array(['75', '50', '20', '35', '400', '500', '55', '65', '70', '250',
       '30', '45', '60', '80', '280', '175', '460', '100', '95', '230',
       '90', '85', '180', '155', '195', '15', '200', '105', '320', '270',
       '370', '110', '240', '220', '210', '380', '410', '420', '40',
       '300', '25', '390', '170', '190', '2000㎡以上', '160', '150', '130',
       '115', '125', '185', '260', '350', '310', '360', '120', '140',
       '135', '165', '490', '670', '520', '290', '145', '1100', '330',
       '620', '550', '680', '430', '810', '470', '910', '1300', '980',
       '710', '590', '340', '1200', '510', '650', '1000', '560', '1700',
       '1400', '1600', '750', '660', '1500', '580', '640', '450', '760',
       '530', '720', '830', '440', '1800', '480', '930', '950', '600',
       '730', '800', '740', '610', '630', '940', '990', '880', '890',
       '920', '780', '790', '970', '870', '770', '960', '700', '690',
       '850', '860', '540', '1900', '570', '820', '840', '10', '900'],
      dtype=object)

In [15]:
df['area'] = pd.to_numeric(df['area'], errors='coerce')

In [16]:
df['area'].unique()

array([  75.,   50.,   20.,   35.,  400.,  500.,   55.,   65.,   70.,
        250.,   30.,   45.,   60.,   80.,  280.,  175.,  460.,  100.,
         95.,  230.,   90.,   85.,  180.,  155.,  195.,   15.,  200.,
        105.,  320.,  270.,  370.,  110.,  240.,  220.,  210.,  380.,
        410.,  420.,   40.,  300.,   25.,  390.,  170.,  190.,   nan,
        160.,  150.,  130.,  115.,  125.,  185.,  260.,  350.,  310.,
        360.,  120.,  140.,  135.,  165.,  490.,  670.,  520.,  290.,
        145., 1100.,  330.,  620.,  550.,  680.,  430.,  810.,  470.,
        910., 1300.,  980.,  710.,  590.,  340., 1200.,  510.,  650.,
       1000.,  560., 1700., 1400., 1600.,  750.,  660., 1500.,  580.,
        640.,  450.,  760.,  530.,  720.,  830.,  440., 1800.,  480.,
        930.,  950.,  600.,  730.,  800.,  740.,  610.,  630.,  940.,
        990.,  880.,  890.,  920.,  780.,  790.,  970.,  870.,  770.,
        960.,  700.,  690.,  850.,  860.,  540., 1900.,  570.,  820.,
        840.,   10.,  900.])

In [18]:
# nanの削除
df = df.dropna(subset=['station_dis', 'area'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15663 entries, 0 to 19895
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             15663 non-null  int64
 1   type              15663 non-null  object
 2   land_type         8439 non-null   object
 3   prefecture        15663 non-null  object
 4   city              15663 non-null  object
 5   city2             15662 non-null  object
 6   station_name      15663 non-null  object
 7   building_year     15663 non-null  int64
 8   station_dis       15663 non-null  float64
 9   price             15663 non-null  int64
 10  price_per_tsubo   0 non-null      float64
 11  room              6812 non-null   object
 12  area              15663 non-null  float64
 13  land_shape        8438 non-null   object
 14  frontage          7820 non-null   float64
 15  gross_floor_area  8336 non-null   object
 16  building_type     15209 non-null  object
 17  city_plan         15600 non-null  object
 18  BCR               15400 non-null  float64
 19  FAR               15400 non-null  float64
 20  Log10_price       15663 non-null  float64
dtypes: float64(7), int64(3), object(11)
memory usage: 2.6+ MB

In [20]:
df

,index,type,land_type,prefecture,city,city2,station_name,building_year,station_dis,price,...,room,area,land_shape,frontage,gross_floor_area,building_type,city_plan,BCR,FAR,Log10_price
0,1,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１１丁目,2016,1.0,37000000,...,３ＬＤＫ,75.0,NaN,NaN,NaN,ＲＣ,商業地域,80.0,600.0,7.568202
1,2,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１１丁目,2012,3.0,57000000,...,２ＬＤＫ,75.0,NaN,NaN,NaN,ＲＣ,商業地域,80.0,600.0,7.755875
2,3,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1981,3.0,17000000,...,２ＬＤＫ,50.0,NaN,NaN,NaN,ＲＣ,商業地域,80.0,400.0,7.230449
3,4,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1977,0.0,3200000,...,１Ｒ,20.0,NaN,NaN,NaN,ＳＲＣ,商業地域,80.0,400.0,6.505150
4,5,中古マンション等,NaN,北海道,札幌市中央区,大通西,西１８丁目,1989,2.0,17000000,...,２ＬＤＫ,50.0,NaN,NaN,NaN,ＳＲＣ,商業地域,80.0,400.0,7.230449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19851,36272,中古マンション等,NaN,沖縄県,那覇市,牧志,美栄橋,2002,6.0,38000000,...,３ＬＤＫ,75.0,NaN,NaN,NaN,ＲＣ,商業地域,80.0,400.0,7.579784
19852,36274,宅地(土地と建物),住宅地,沖縄県,那覇市,字松川,市立病院前(沖縄),2022,9.0,44000000,...,NaN,120.0,ほぼ長方形,9.0,95,木造,第１種低層住居専用地域,50.0,100.0,7.643453
19853,36275,中古マンション等,NaN,沖縄県,那覇市,銘苅,古島,2019,3.0,58000000,...,３ＬＤＫ,80.0,NaN,NaN,NaN,ＲＣ,第２種住居地域,60.0,200.0,7.763428
19854,36276,中古マンション等,NaN,沖縄県,那覇市,寄宮,安里,1990,15.0,15000000,...,２ＤＫ,50.0,NaN,NaN,NaN,ＲＣ,第１種中高層住居専用地域,60.0,200.0,7.176091
19895,36378,宅地(土地と建物),商業地,沖縄県,中頭郡西原町,字翁長,てだこ浦西,1986,10.0,230000000,...,NaN,1100.0,ほぼ台形,26.0,2000㎡以上,ＲＣ,第１種住居地域,60.0,200.0,8.361728